# Generated by Django 5.1.1 on 2024-11-22 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massege', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_masseges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='NGcN2K5xtDUDpPqo2S7jWj67aS3EbuG5rqhbZewGkmW4SV9f1bfHItGejVog5zFfZXGoJpAVkvOfK1nXLpbB', unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='chats', to=settings.AUTH_USER_MODEL)),
                ('masseges', models.ManyToManyField(blank=True, related_name='chat', to='messenger.massage')),
            ],
        ),
    ]
