# Generated by Django 5.1.1 on 2024-11-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='mVCNQUmE8yUv3BUyVSyWttTot0Gm0Gi0IAoavoDAaVAhsG6tQuvED7egsz3OX29', unique=True),
        ),
    ]
