# Generated by Django 5.1.1 on 2024-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='MPEonrmgR0FDtPBrkxL9jKXpH25dy2RpPm7tebw6zgQez1XHtGjXFFD1CAbDjXQHyzBktCZwlq1ePEbIL', max_length=200, unique=True),
        ),
    ]
