# Generated by Django 5.1.1 on 2024-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='XBinaK0ERwtVi3WFpkt0Bxhe3BSWXDrf2znK0UDEcycOy16xUizyHQdqcJECC6Te2HMEPa5AcmJt1Fk', max_length=200, unique=True),
        ),
    ]
