# Generated by Django 5.1.6 on 2025-02-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='98hxTjCkbrOtBSmJQjdp6cHuvhOvwK9g2e3TwemU6fuBTLLPf1XKT5Xc', max_length=200, unique=True),
        ),
    ]
