# Generated by Django 5.1.6 on 2025-02-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='WfZggpZYTkl7dZNBSJU5JBTACCmLvKhddG3GdVLt2GfLdxzFShNhOUzCnIHIJICAj1bx4gM3QbR44SAyIe0XDMpCMwI97tyv', max_length=200, unique=True),
        ),
    ]
