# Generated by Django 5.1.6 on 2025-02-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='427dK8vnhBG1pwt0LFasBJNcUyGqdTGJaPh55D3iCyo4D2YkVoMDaqON0Y4rmtxcYkiYBxc5CLLUGgsjenBV2YuIg7CDu', max_length=200, unique=True),
        ),
    ]
