# Generated by Django 5.1.6 on 2025-02-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='fl8yKWGhZ23tPWPZUj9gntxt97YkWzTBV1smtb3UwWalh7NBCJ8PW7AIXXj9V0GgHiy9jnZ6h3NOq2U8EbE9Mu5ch59ejdc', max_length=200, unique=True),
        ),
    ]
