# Generated by Django 5.1.6 on 2025-02-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='T9wWAE5uPgn9PZL84zBQxtLU3wXkud2lQeWkxbZ6n9t1PkV2MeaKkOwDutn9R86C7P75DVQlYTA9', max_length=200, unique=True),
        ),
    ]
