# Generated by Django 5.1.6 on 2025-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='gVLfF1D2d1NI2Pz3J4MB9VfpUgaQ6ko3mIR6aBCCLQO3S41u5ZNPA2AoXgvqlMxVL1qWL8bKZKeqHMOuLj', max_length=200, unique=True),
        ),
    ]
