# Generated by Django 5.1.6 on 2025-03-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='hT8zVppylcGWDserG1ths5IbsNOOQPYJP52v1lQlqPDH6nSov9u', max_length=200, unique=True),
        ),
    ]
