# Generated by Django 5.1.6 on 2025-03-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='M32Ah5bxnoUqnsSwOzuVIChpGg9Bn1Xvx7hMKdMpvvEGpQT9WMeQIWlTCh5hXD24j', max_length=200, unique=True),
        ),
    ]
