# Generated by Django 5.1.6 on 2025-03-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='HVaOzOEzvsjTF5SKQk024wfd7KJ853RDlgWQfLguR1JWKxYTlMt7Ui66GfxW1XjD1IK6TFCTnboKsW85DGCU0y4', max_length=200, unique=True),
        ),
    ]
