# Generated by Django 5.1.6 on 2025-03-01 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_alter_chat_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='ZHExrGQAXoyNuSYRyjI4or7z8hhbZ6XdE4asbZUT66yLUXvo6VaubajH8iDLlltAgw8aF9ztU0CgmJ4Vw', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='massage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_masseges', to=settings.AUTH_USER_MODEL),
        ),
    ]
