# Generated by Django 5.1.6 on 2025-03-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_alter_chat_slug_alter_massage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='4OXNzhgyDK1aotY9DkFSkvSfQTwUholKntFhCu1Hf7Kd3jAj1VWa0u91CW', max_length=200, unique=True),
        ),
    ]
