# Generated by Django 5.1.6 on 2025-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='LQIFkc4cDK7PNOhfNG2l1Vit0jJzFz8jysI2Y9wjV2XqVvRdfNarmGcrYsYm2dq4uw0ssT', max_length=200, unique=True),
        ),
    ]
