# Generated by Django 5.1.6 on 2025-03-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0017_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='ivzoLMKmeWgzn33tS5p8r4quaYJXvKLVT3BsRkG9AL84qx85bY0', max_length=200, unique=True),
        ),
    ]
