# Generated by Django 5.1.6 on 2025-03-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_alter_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='HFpnO330Ge9AiMXObD0Oeoy4AdWcxJQjakm7ZAUmYQ8yGVvcRJmwO9SJzDDYTr4e06LIfVhGfl5RfaXC2h', max_length=200, unique=True),
        ),
    ]
