# Generated by Django 5.1.6 on 2025-03-05 13:54

import django.db.models.deletion
import modules.generators.strings
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0019_alter_chat_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='masseges',
        ),
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default=modules.generators.strings.generate_random_string, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('send_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.chat')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Massage',
        ),
    ]
