# Generated by Django 5.1.6 on 2025-03-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0003_alter_image_author'),
        ('messenger', '0020_remove_chat_masseges_alter_chat_slug_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='messages', to='cdn.image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
