# Generated by Django 5.1.1 on 2024-09-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_validatedemails_rename_dete_usergoods_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatedemails',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
