# Generated by Django 5.1.1 on 2024-09-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_validatedemails_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatedemails',
            name='slug',
        ),
        migrations.AddField(
            model_name='validatedemails',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
