# Generated by Django 5.1.1 on 2024-11-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_avatar_alter_store_slug'),
        ('user', '0006_user_slug_alter_user_avatar_mailcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoods',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.goods'),
            preserve_default=False,
        ),
    ]
