# Generated by Django 5.1.1 on 2024-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoods',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
