# Generated by Django 5.1.6 on 2025-03-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_cart_remove_user_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoods',
            name='count',
        ),
    ]
