# Generated by Django 5.1.6 on 2025-03-01 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_usergoods_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cart', to='user.usergoods'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_favorites', to='user.usergoods'),
        ),
        migrations.AlterField(
            model_name='user',
            name='views_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_views_history', to='user.usergoods'),
        ),
    ]
