# Generated by Django 5.1.6 on 2025-03-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_goods_gallery_delete_gallery'),
        ('user', '0012_alter_user_cart_alter_user_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoods',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.goods'),
        ),
    ]
