# Generated by Django 5.1.6 on 2025-03-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0003_alter_image_author'),
        ('user', '0014_alter_mailcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='cdn.image'),
        ),
    ]
