# Generated by Django 5.1.1 on 2024-11-22 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('bucket_name', models.CharField(blank=True, max_length=300)),
                ('application_key_id', models.CharField(blank=True, max_length=300)),
                ('application_key', models.CharField(blank=True, max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_server', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Хмари',
                'verbose_name_plural': 'Хмару',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(blank=True, null=True, upload_to='static')),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
                ('cloud', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='cdn.cloud')),
            ],
            options={
                'verbose_name': 'Картинку',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
