# Generated by Django 5.0.6 on 2024-07-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='goods',
        ),
        migrations.AddField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='store.store'),
            preserve_default=False,
        ),
    ]
