# Generated by Django 5.1.1 on 2024-11-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_gallery_path_gallery_img_goods_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='social_links',
            field=models.ManyToManyField(blank=True, related_name='store', to='store.usersocialmedia'),
        ),
    ]
