# Generated by Django 5.1.1 on 2024-11-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0001_initial'),
        ('store', '0004_alter_store_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_image', to='cdn.image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
