# Generated by Django 5.1.6 on 2025-02-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0002_alter_image_slug'),
        ('store', '0008_alter_goods_author_alter_goods_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='goods_images', to='cdn.image'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
