# Generated by Django 5.1.6 on 2025-03-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='name_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristic', to='store.characteristicnametype'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='store.store'),
        ),
        migrations.AlterField(
            model_name='usersocialmedia',
            name='social',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_social_media', to='store.socialmedia'),
        ),
    ]
