# Generated by Django 5.1.6 on 2025-03-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_characteristic_name_type_alter_goods_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='store.store'),
        ),
    ]
